@file:OptIn(ExperimentalJsExport::class)
@file:DivaJsExport

package io.github.juevigrace.diva.lib.models.permission

import io.github.juevigrace.diva.core.DivaJsExport
import kotlin.js.ExperimentalJsExport

enum class PermissionAction {
    PERMISSION_NONE,

    PERMISSION_USERS_READ,
    PERMISSION_USERS_WRITE,
    PERMISSION_USERS_EMAIL_UPDATE,
    PERMISSION_USERS_PHONE_UPDATE,
    PERMISSION_USERS_USERNAME_UPDATE,
    PERMISSION_USERS_PASSWORD_UPDATE,
    PERMISSION_USERS_ROLE_UPDATE,
    PERMISSION_USERS_VERIFIED_UPDATE,
    PERMISSION_USERS_RESTORE_WRITE,
    PERMISSION_USERS_PROFILE_CREATE,

    PERMISSION_USERS_PREFERENCES_READ,
    PERMISSION_USERS_PREFERENCES_CREATE,

    PERMISSION_SESSIONS_READ,
    PERMISSION_SESSIONS_WRITE,

    PERMISSION_DEVICES_READ,

    PERMISSION_ACTIONS_READ,
    PERMISSION_ACTIONS_WRITE,

    PERMISSION_USER_PERMISSIONS_READ,
    PERMISSION_USER_PERMISSIONS_WRITE,

    PERMISSION_PERMISSIONS_READ,
    PERMISSION_PERMISSIONS_WRITE,

    PERMISSION_OWNERSHIP_BYPASS,
}

fun safePermissionAction(value: String): PermissionAction {
    return try {
        PermissionAction.valueOf(value)
    } catch (_: IllegalArgumentException) {
        PermissionAction.PERMISSION_NONE
    }
}
