// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_device.sql

package sqli

import (
	"context"
)

const createUserDevice = `-- name: CreateUserDevice :exec
insert into diva_user_device (
    user_id,
    device_id
) values (
    ?,
    ?
)
`

type CreateUserDeviceParams struct {
	UserID   string
	DeviceID string
}

func (q *Queries) CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createUserDevice, arg.UserID, arg.DeviceID)
	return err
}

const deleteUserDevice = `-- name: DeleteUserDevice :exec
delete from diva_user_device
where user_id = ? and device_id = ?
`

type DeleteUserDeviceParams struct {
	UserID   string
	DeviceID string
}

func (q *Queries) DeleteUserDevice(ctx context.Context, arg DeleteUserDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserDevice, arg.UserID, arg.DeviceID)
	return err
}

const getUserDevice = `-- name: GetUserDevice :one
select
    ud.user_id,
    ud.device_id,
    ud.created_at,
    ud.updated_at
from diva_user_device ud
where ud.user_id = ? and ud.device_id = ?
`

type GetUserDeviceParams struct {
	UserID   string
	DeviceID string
}

func (q *Queries) GetUserDevice(ctx context.Context, arg GetUserDeviceParams) (DivaUserDevice, error) {
	row := q.db.QueryRowContext(ctx, getUserDevice, arg.UserID, arg.DeviceID)
	var i DivaUserDevice
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserDevices = `-- name: ListUserDevices :many
select
    ud.user_id,
    ud.device_id,
    ud.created_at,
    ud.updated_at
from diva_user_device ud
where ud.user_id = ?
order by ud.updated_at desc
`

func (q *Queries) ListUserDevices(ctx context.Context, userID string) ([]DivaUserDevice, error) {
	rows, err := q.db.QueryContext(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserDevice
	for rows.Next() {
		var i DivaUserDevice
		if err := rows.Scan(
			&i.UserID,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
