# style
kotlin.code.style=official

# performance
org.gradle.jvmargs=-Xmx2048M -Xms512m -XX\:+UseG1GC -XX\:+UseStringDeduplication -XX\:MaxGCPauseMillis\=200 -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx1536m,-Xms512m,-XX\:MaxMetaspaceSize\=512m,-XX\:+UseG1GC" -Dkotlin.daemon.options\="autoshutdownIdleSeconds\=1800"
kotlin.daemon.jvmargs=-Xms512m -Xmx1536m -XX\:+UseG1GC -XX\:+UseStringDeduplication -XX\:MaxMetaspaceSize\=512m -XX\:+HeapDumpOnOutOfMemoryError

#gradle
org.gradle.daemon=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache.parallel=true
org.gradle.kotlin.dsl.allWarningsAsErrors=true
org.gradle.configuration-cache.problems=warn
org.gradle.dependency.verification=LENIENT
org.gradle.vfs.watch=true
