[versions]
diva-app-name = "1.0.0"
diva-app-code = "1"
diva-lib = "1.0.0"
diva-framework = "0.0.23"
agp = "9.4.0"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"
androidx-espresso = "3.7.0"
androidx-test = "1.7.0"
androidx-activity = "1.13.0"
androidx-core = "1.19.0"
lifecycle = "2.11.0"
material3-adaptive = "1.3.0-beta02"
savedstate = "1.4.0"
window = "1.5.1"
material3 = "1.9.0"
compose-hot-reload = "1.2.0"
compose-multiplatform = "1.12.0"
kotlin = "2.4.10"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0"
kotlinx-serialization = "1.11.0"
koin = "4.2.2"
ktor = "3.5.2"
logback = "1.6.3"
maven-publish = "0.37.0"
nav3-ui = "1.1.1"
sqldelight = "2.3.2"
sqlite = "3.53.2.1"
postgresql = "42.7.13"
mysql = "26.7.0"
hikari = "7.1.0"
testcontainers = "1.21.4"
secrets = "2.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
######### [TEST DEPENDENCIES] #########

kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test" }

######### [GRADLE PLUGIN DEPENDENCIES] #########

android-tools-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
jetbrains-compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
secrets-gradle = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref = "secrets" }

######### [DIVA DEPENDENCIES] #########
diva-core = { group = "io.github.juevigrace", name = "diva-core", version.ref = "diva-framework" }
diva-database = { group = "io.github.juevigrace", name = "diva-database", version.ref = "diva-framework" }
diva-database-sqlite = { group = "io.github.juevigrace", name = "diva-database-sqlite", version.ref = "diva-framework" }
diva-database-postgres = { group = "io.github.juevigrace", name = "diva-database-postgres", version.ref = "diva-framework" }
diva-database-mysql = { group = "io.github.juevigrace", name = "diva-database-mysql", version.ref = "diva-framework" }
diva-network = { group = "io.github.juevigrace", name = "diva-network", version.ref = "diva-framework" }
diva-ui = { group = "io.github.juevigrace", name = "diva-ui", version.ref = "diva-framework" }
diva-lib-core = { group = "io.github.juevigrace", name = "diva-lib-core", version.ref = "diva-lib" }
diva-lib-database = { group = "io.github.juevigrace", name = "diva-lib-database", version.ref = "diva-lib" }
diva-lib-ui = { group = "io.github.juevigrace", name = "diva-lib-ui", version.ref = "diva-lib" }
diva-lib-models-api = { group = "io.github.juevigrace", name = "diva-lib-models-api", version.ref = "diva-lib" }
diva-lib-models-core = { group = "io.github.juevigrace", name = "diva-lib-models-core", version.ref = "diva-lib" }
diva-lib-auth = { group = "io.github.juevigrace", name = "diva-lib-auth", version.ref = "diva-lib" }
diva-lib-user = { group = "io.github.juevigrace", name = "diva-lib-user", version.ref = "diva-lib" }

######### [ANDROIDX DEPENDENCIES] #########

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }

######### [KOIN DEPENDENCIES] #########

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }

######### [KOTLIN/KOTLINX DEPENDENCIES] #########

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core-js = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-js", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

######### [KTOR DEPENDENCIES] #########

ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktor-client-curl = { group = "io.ktor", name = "ktor-client-curl", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-winhttp = { group = "io.ktor", name = "ktor-client-winhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

######### [SQLDELIGHT DEPENDENCIES] #########

sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-async-extensions = { group = "app.cash.sqldelight", name = "async-extensions", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
sqldelight-native-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-jdbc-driver = { group = "app.cash.sqldelight", name = "jdbc-driver", version.ref = "sqldelight" }
sqldelight-r2dbc-driver = { group = "app.cash.sqldelight", name = "r2dbc-driver", version.ref = "sqldelight" }
sqldelight-web-worker-driver = { group = "app.cash.sqldelight", name = "web-worker-driver", version.ref = "sqldelight" }
sqldelight-web-worker-driver-wasm-js = { group = "app.cash.sqldelight", name = "web-worker-driver-wasm-js", version.ref = "sqldelight" }
sqldelight-mysql-dialect = { group = "app.cash.sqldelight", name = "mysql-dialect", version.ref = "sqldelight" }
sqldelight-postgres-dialect = { group = "app.cash.sqldelight", name = "postgresql-dialect", version.ref = "sqldelight" }

######### [COMPOSE DEPENDENCIES] #########

compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose-multiplatform" }
compose-animation-graphics = { group = "org.jetbrains.compose.animation", name = "animation-graphics", version.ref = "compose-multiplatform" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose-multiplatform" }
compose-runtime-saveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "compose-multiplatform" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose-multiplatform" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose-multiplatform" }
compose-ui-util = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "compose-multiplatform" }
compose-ui-test = { group = "org.jetbrains.compose.ui", name = "ui-test", version.ref = "compose-multiplatform" }
compose-ui-test-junit4 = { group = "org.jetbrains.compose.ui", name = "ui-test-junit4", version.ref = "compose-multiplatform" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-desktop-common = { group = "org.jetbrains.compose.desktop", name = "desktop", version.ref = "compose-multiplatform" }

material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
material3-adaptive-navigation-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite" , version.ref = "material3" }
material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-nav3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3-adaptive" }
material3-window-size = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "material3" }

nav3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "nav3-ui" }

######### [SAVEDSTATE DEPENDENCIES] #########

savedstate = { group = "org.jetbrains.androidx.savedstate", name = "savedstate", version.ref = "savedstate" }
savedstate-compose = { group = "org.jetbrains.androidx.savedstate", name = "savedstate-compose", version.ref = "savedstate" }

######### [WINDOW DEPENDENCIES] #########

window-core = { group = "org.jetbrains.androidx.window", name = "window-core", version.ref = "window" }

######### [LIFECYCLE DEPENDENCIES] #########

lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-viewmodel-nav3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }

######### [OTHER THIRD-PARTY DEPENDENCIES] #########

logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }

######### [TESTCONTAINERS DEPENDENCIES] #########

testcontainers-jdbc = { group = "org.testcontainers", name = "jdbc", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
testcontainers-mysql = { group = "org.testcontainers", name = "mysql", version.ref = "testcontainers" }