// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package sqli

import (
	"context"
)

const createDevice = `-- name: CreateDevice :exec
insert into diva_devices (
    id,
    name
) values (
    ?,
    ?
)
`

type CreateDeviceParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice, arg.ID, arg.Name)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
;

select
    d.id,
    d.name,
    d.created_at,
    d.updated_at
from diva_devices d
where d.id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (DivaDevice, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i DivaDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByName = `-- name: GetDeviceByName :one
select
    d.id,
    d.name,
    d.created_at,
    d.updated_at
from diva_devices d
where d.name = ?
`

func (q *Queries) GetDeviceByName(ctx context.Context, name string) (DivaDevice, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByName, name)
	var i DivaDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDevices = `-- name: ListAllDevices :many
;

select
    d.id,
    d.name,
    d.created_at,
    d.updated_at
from diva_devices d
order by d.name asc
`

func (q *Queries) ListAllDevices(ctx context.Context) ([]DivaDevice, error) {
	rows, err := q.db.QueryContext(ctx, listAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaDevice
	for rows.Next() {
		var i DivaDevice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
